version: '3.1' 
services: 
sonar-server: 
image: sonarqube:8.9.1-community 
ports: 
- 9000:9000 
   
sonar-scanner: 
image: maven:3.6.3-openjdk-8  
build: 
context: . 
dockerfile: Dockerfile 
depends_on: 
- sonar-server It was originally published on https://www.apriorit.com/
